FROM docker.io/accetto/ubuntu-vnc-xfce-opengl-g3
USER root

RUN apt-get update && apt-get install -y git unzip ca-certificates python3-pip

ADD 3.0 /home/headless/blenders/3.0

ENTRYPOINT [ "/usr/bin/tini", "--", "/dockerstartup/startup.sh" ]
