name: build

env:
  BLENDER_2_93: https://download.blender.org/release/Blender2.93/blender-2.93.18-linux-x64.tar.xz
  BLENDER_3_0: https://download.blender.org/release/Blender3.0/blender-3.0.1-linux-x64.tar.xz
  BLENDER_3_1: https://download.blender.org/release/Blender3.1/blender-3.1.2-linux-x64.tar.xz
  BLENDER_3_2: https://download.blender.org/release/Blender3.2/blender-3.2.2-linux-x64.tar.xz
  BLENDER_3_3: https://download.blender.org/release/Blender3.3/blender-3.3.19-linux-x64.tar.xz #LTS
  BLENDER_3_4: https://download.blender.org/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz
  BLENDER_3_5: https://download.blender.org/release/Blender3.5/blender-3.5.1-linux-x64.tar.xz
  BLENDER_3_6: https://download.blender.org/release/Blender3.6/blender-3.6.12-linux-x64.tar.xz #LTS
  BLENDER_4_0: https://download.blender.org/release/Blender4.0/blender-4.0.2-linux-x64.tar.xz
  BLENDER_4_1: https://download.blender.org/release/Blender4.1/blender-4.1.1-linux-x64.tar.xz

on:
  push:
      branches: [ main ]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  Blender-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Build.py
        run: python3 build.py
