name: build

on:
  push:
      branches: [ main ]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  MULTI_VERSION:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
            PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD

      - name: Download Blender 2.93
        run: curl https://download.blender.org/release/Blender2.93/blender-2.93.13-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 2.93 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 2.93 --strip-components=1

      - name: Download Blender 3.0
        run: curl https://download.blender.org/release/Blender3.0/blender-3.0.1-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.0 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.0 --strip-components=1

      - name: Download Blender 3.1
        run: curl https://download.blender.org/release/Blender3.1/blender-3.1.2-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.1 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.1 --strip-components=1

      - name: Download Blender 3.2
        run: curl https://download.blender.org/release/Blender3.2/blender-3.2.2-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.2 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.2 --strip-components=1

      - name: Download Blender 3.3
        run: curl https://download.blender.org/release/Blender3.3/blender-3.3.2-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.3 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.3 --strip-components=1

      - name: Download Blender 3.4
        run: curl https://download.blender.org/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.4 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.4 --strip-components=1

      - name: BUILD
        run: podman build -f ./Containerfile -t agajdosi/headless-blender:multi-version
      - name: PUSH
        run: podman push agajdosi/headless-blender:multi-version

  Blender_2-93:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender2.93/blender-2.93.13-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-2.93
      - name: Push
        run: podman push agajdosi/headless-blender:blender-2.93

  Blender_3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender3.0/blender-3.0.1-linux-x64.tar.xz -o blender.tar.xz
      - name: mkdir
        run: mkdir single-version/blender -p
      - name: Extract Blender
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-3.0
      - name: Push
        run: podman push agajdosi/headless-blender:blender-3.0

  Blender_3-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender3.1/blender-3.1.2-linux-x64.tar.xz -o blender.tar.xz
      - name: mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-3.1
      - name: Push
        run: podman push agajdosi/headless-blender:blender-3.1

  Blender_3-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender3.2/blender-3.2.2-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-3.2
      - name: Push
        run: podman push agajdosi/headless-blender:blender-3.2

  Blender_3-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender3.3/blender-3.3.2-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-3.3
      - name: push
        run: podman push agajdosi/headless-blender:blender-3.3

  Blender_3-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl https://download.blender.org/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t agajdosi/headless-blender:blender-3.4
      - name: push
        run: podman push agajdosi/headless-blender:blender-3.4
