name: build

env:
  BLENDER_2_93: https://download.blender.org/release/Blender2.93/blender-2.93.18-linux-x64.tar.xz
  BLENDER_3_0: https://download.blender.org/release/Blender3.0/blender-3.0.1-linux-x64.tar.xz
  BLENDER_3_1: https://download.blender.org/release/Blender3.1/blender-3.1.2-linux-x64.tar.xz
  BLENDER_3_2: https://download.blender.org/release/Blender3.2/blender-3.2.2-linux-x64.tar.xz
  BLENDER_3_3: https://download.blender.org/release/Blender3.3/blender-3.3.10-linux-x64.tar.xz
  BLENDER_3_4: https://download.blender.org/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz
  BLENDER_3_5: https://download.blender.org/release/Blender3.5/blender-3.5.1-linux-x64.tar.xz
  BLENDER_3_6: https://download.blender.org/release/Blender3.6/blender-3.6.2-linux-x64.tar.xz
  BLENDER_4_0: https://builder.blender.org/download/daily/blender-4.0.0-alpha+main.6e20beba22df-linux.x86_64-release.tar.xz

on:
  push:
      branches: [ main ]
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  MULTI_VERSION:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
            PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD

      - name: Download Blender 2.93
        run: curl $BLENDER_2_93 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 2.93 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 2.93 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_2_93 -t blender_2_93:latest
      - name: Delete Blender
        run: rm -rf 2.93
      #- name: Delete previous docker image
      #  run: docker rmi daccetto/ubuntu-vnc-xfce-opengl-g3

      - name: Download Blender 3.0
        run: curl $BLENDER_3_0 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.0 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.0 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_0 -t blender_3_0:latest
      - name: Delete Blender
        run: rm -rf 3.0
      #- name: Delete previous docker image
      #  run: docker rmi blender_2_93

      - name: Download Blender 3.1
        run: curl $BLENDER_3_1 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.1 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.1 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_1 -t blender_3_1:latest
      - name: Delete Blender
        run: rm -rf 3.1
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_0

      - name: Download Blender 3.2
        run: curl $BLENDER_3_2 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.2 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.2 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_2 -t blender_3_2:latest
      - name: Delete Blender
        run: rm -rf 3.2
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_1

      - name: Download Blender 3.3
        run: curl $BLENDER_3_3 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.3 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.3 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_3 -t blender_3_3:latest
      - name: Delete Blender
        run: rm -rf 3.3
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_2

      - name: Download Blender 3.4
        run: curl $BLENDER_3_4 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.4 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.4 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_4 -t blender_3_4:latest
      - name: Delete Blender
        run: rm -rf 3.4
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_3

      - name: Download Blender 3.5
        run: curl $BLENDER_3_5 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.5 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.5 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_5 -t blender_3_5:latest
      - name: Delete Blender
        run: rm -rf 3.5
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_4

      - name: Download Blender 3.6
        run: curl $BLENDER_3_6 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 3.6 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 3.6 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz
      - name: BUILD
        run: podman build -f ./Containerfile-blender_3_6 -t blender_3_6:latest
      - name: Delete Blender
        run: rm -rf 3.6
      #- name: Delete previous docker image
      #  run: docker rmi blender_3_5
      
      - name: Download Blender 4.0
        run: curl $BLENDER_4_0 -o blender.tar.xz
      - name: Mkdir
        run: mkdir 4.0 -p
      - name: Extract
        run: tar -xf blender.tar.xz -C 4.0 --strip-components=1
      - name: Delete tar file
        run: rm blender.tar.xz

      - name: FINAL BUILD
        run: podman build -f ./Containerfile-blender_4_0 -t blenderkit/headless-blender:multi-version
      - name: PUSH
        run: podman push blenderkit/headless-blender:multi-version

  Blender_2-93:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_2_93 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-2.93
      - name: Push
        run: podman push blenderkit/headless-blender:blender-2.93

  Blender_3-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_0 -o blender.tar.xz
      - name: mkdir
        run: mkdir single-version/blender -p
      - name: Extract Blender
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.0
      - name: Push
        run: podman push blenderkit/headless-blender:blender-3.0

  Blender_3-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_1 -o blender.tar.xz
      - name: mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.1
      - name: Push
        run: podman push blenderkit/headless-blender:blender-3.1

  Blender_3-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_2 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: Build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.2
      - name: Push
        run: podman push blenderkit/headless-blender:blender-3.2

  Blender_3-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_3 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.3
      - name: push
        run: podman push blenderkit/headless-blender:blender-3.3

  Blender_3-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_4 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.4
      - name: push
        run: podman push blenderkit/headless-blender:blender-3.4

  Blender_3-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_5 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.5
      - name: push
        run: podman push blenderkit/headless-blender:blender-3.5

  Blender_3-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_3_6 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-3.6
      - name: push
        run: podman push blenderkit/headless-blender:blender-3.6

  Blender_4-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: sudo apt-get -y update && sudo apt-get -y install podman
      - name: Login
        env:
          PASSWORD: ${{ secrets.AGAJDOSI_DOCKERHUB_SECRET }}
        run: podman login docker.io -u agajdosi -p $PASSWORD
      - name: Download
        run: curl $BLENDER_4_0 -o blender.tar.xz
      - name: Mkdir
        run: mkdir single-version/blender -p
      - name: Extract
        run: tar -xf blender.tar.xz -C single-version/blender --strip-components=1
      - name: build
        run: podman build -f ./single-version/Containerfile -t blenderkit/headless-blender:blender-4.0
      - name: push
        run: podman push blenderkit/headless-blender:blender-4.0
